const fs = require('fs');
let data = fs.readFileSync('src/data/initialData.ts', 'utf8');

const additionalParcels = `
  {
    id: 'LP-001',
    surveyNumber: '11/1',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 2.5,
    landType: 'Agricultural (Dry)',
    ownerName: 'R. K. Sharma',
    ownerReferenceMasked: 'R. K. S****a (***1234)',
    ownershipType: 'Private Individual',
    status: 'Acquired',
    compensationStatus: 'Award Declared',
    possessionStatus: 'Pending',
    marketValuePerAcre: 2000000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Verified',
    latitude: 12.74,
    longitude: 77.82,
  },
  {
    id: 'LP-002',
    surveyNumber: '11/2',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 1.5,
    landType: 'Agricultural (Wet)',
    ownerName: 'M. Patel',
    ownerReferenceMasked: 'M. P****l (***5678)',
    ownershipType: 'Private Individual',
    status: 'Acquired',
    compensationStatus: 'Disbursed',
    possessionStatus: 'Pending',
    marketValuePerAcre: 2500000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Verified',
    latitude: 12.75,
    longitude: 77.83,
  },
  {
    id: 'LP-003',
    surveyNumber: '11/3',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 3.0,
    landType: 'Commercial',
    ownerName: 'S. Singh',
    ownerReferenceMasked: 'S. S****h (***9012)',
    ownershipType: 'Private Individual',
    status: 'Survey / Notification',
    compensationStatus: 'Not Assessed',
    possessionStatus: 'Pending',
    marketValuePerAcre: 5000000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Pending Verification',
    latitude: 12.76,
    longitude: 77.84,
  },
  {
    id: 'LP-004',
    surveyNumber: '11/4',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 1.0,
    landType: 'Residential',
    ownerName: 'A. Kumar',
    ownerReferenceMasked: 'A. K****r (***3456)',
    ownershipType: 'Private Individual',
    status: 'Acquired',
    compensationStatus: 'Disbursed',
    possessionStatus: 'Possession Taken',
    marketValuePerAcre: 4000000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Verified',
    latitude: 12.77,
    longitude: 77.85,
  },
  {
    id: 'LP-005',
    surveyNumber: '11/5',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 2.0,
    landType: 'Agricultural (Dry)',
    ownerName: 'P. Verma',
    ownerReferenceMasked: 'P. V****a (***7890)',
    ownershipType: 'Private Individual',
    status: 'Acquired',
    compensationStatus: 'Award Declared',
    possessionStatus: 'Notice Issued',
    marketValuePerAcre: 2200000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Verified',
    latitude: 12.78,
    longitude: 77.86,
  },
  {
    id: 'LP-006',
    surveyNumber: '11/6',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 1.2,
    landType: 'Commercial',
    ownerName: 'L. Gupta',
    ownerReferenceMasked: 'L. G****a (***2345)',
    ownershipType: 'Private Individual',
    status: 'Pending Section 11',
    compensationStatus: 'Not Assessed',
    possessionStatus: 'Pending',
    marketValuePerAcre: 4500000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Pending Verification',
    latitude: 12.79,
    longitude: 77.87,
  },
  {
    id: 'LP-007',
    surveyNumber: '11/7',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 0.8,
    landType: 'Residential',
    ownerName: 'N. Reddy',
    ownerReferenceMasked: 'N. R****y (***6789)',
    ownershipType: 'Private Individual',
    status: 'Award / Compensation',
    compensationStatus: 'PFMS Processing',
    possessionStatus: 'Pending',
    marketValuePerAcre: 3500000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Verified',
    latitude: 12.80,
    longitude: 77.88,
  },
  {
    id: 'LP-010',
    surveyNumber: '11/10',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 1.5,
    landType: 'Agricultural (Wet)',
    ownerName: 'T. Rao',
    ownerReferenceMasked: 'T. R** (***1122)',
    ownershipType: 'Private Individual',
    status: 'Acquired',
    compensationStatus: 'Disbursed',
    possessionStatus: 'Possession Taken',
    marketValuePerAcre: 2600000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Verified',
    latitude: 12.81,
    longitude: 77.89,
  },
  {
    id: 'LP-015',
    surveyNumber: '11/15',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 2.1,
    landType: 'Agricultural (Dry)',
    ownerName: 'H. Das',
    ownerReferenceMasked: 'H. D*s (***3344)',
    ownershipType: 'Private Individual',
    status: 'Acquired',
    compensationStatus: 'Disbursed',
    possessionStatus: 'Possession Taken',
    marketValuePerAcre: 2100000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Verified',
    latitude: 12.82,
    longitude: 77.90,
  },
  {
    id: 'LP-020',
    surveyNumber: '11/20',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 3.5,
    landType: 'Commercial',
    ownerName: 'V. Iyer',
    ownerReferenceMasked: 'V. I**r (***5566)',
    ownershipType: 'Private Individual',
    status: 'Award / Compensation',
    compensationStatus: 'Disputed / In Escrow',
    possessionStatus: 'Pending',
    marketValuePerAcre: 5500000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Disputed',
    latitude: 12.83,
    longitude: 77.91,
  },
  {
    id: 'LP-025',
    surveyNumber: '11/25',
    projectId: 'PRJ-2025-0101',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    tehsil: 'Hosur',
    village: 'Zuzuvadi',
    areaAcres: 1.8,
    landType: 'Residential',
    ownerName: 'C. Nair',
    ownerReferenceMasked: 'C. N**r (***7788)',
    ownershipType: 'Private Individual',
    status: 'Section 19 Declaration',
    compensationStatus: 'Not Assessed',
    possessionStatus: 'Pending',
    marketValuePerAcre: 3800000,
    coordinates: { x: 100, y: 100 },
    externalLandRecordSource: 'Tamil Nilam',
    mutationStatus: 'Verified',
    latitude: 12.84,
    longitude: 77.92,
  },
`;

data = data.replace('export const INITIAL_PARCELS: LandParcel[] = [', 'export const INITIAL_PARCELS: LandParcel[] = [' + additionalParcels);
fs.writeFileSync('src/data/initialData.ts', data);
